[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
monitor = { path = "../../crates/monitor" }
config = { workspace = true }
serde = { workspace = true, features = ["derive"] }
