[package]
name = "plethora_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
monitor = { path = "../../crates/monitor" }

alloy = { workspace = true }
alloy-chains = { workspace = true }
dotenvy = { workspace = true }
foundry-block-explorers = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
serde_json = { workspace = true }
futures-util = { workspace = true }
