[package]
name = "plethora_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
monitor = { path = "../../crates/monitor" }
config = { path = "../../crates/config" }
server = { path = "../../crates/server" }

alloy = { workspace = true }
alloy-chains = { workspace = true }
axum = { workspace = true }
dotenvy = { workspace = true }
foundry-block-explorers = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
serde_json = { workspace = true }
